name: web_components
version: 0.12.2
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
homepage: https://github.com/dart-lang/web-components/
description: >
  Polyfills for Shadow DOM, Custom Elements, and HTML Imports.
  Custom Elements let authors define their own elements. Authors associate code
  with custom tag names, and then use those custom tag names as they would any
  standard tag. Shadow DOM is designed to provide encapsulation for custom
  elements, by hiding DOM subtrees under shadow roots. HTML Imports let authors
  bundle code and HTML as if they were libraries.
dependencies:
  analyzer: '^0.27.0'
  barback: '>=0.14.2 <0.16.0'
  code_transformers: '^0.3.0'
  html: '^0.12.0'
  initialize: '^0.6.0'
  path: '^1.3.0'
dev_dependencies:
  test: '^0.12.0'
  browser: '^0.10.0'
transformers:
- web_components/build/mirrors_remover:
    $include: 'lib/src/init.dart'
- web_components:
    $include: '**/*_test.html'
    entry_points:
      - test/custom_element_test.html
      - test/custom_element_proxy_test.html
      - test/html_import_annotation_test.html
      - test/init_web_components_test.html
- test/pub_serve:
    $include: test/**_test{.*,}.dart

environment:
  sdk: ">=1.9.0-dev.7.1 <2.0.0"
